import type { Metadata } from "next";
import "./globals.css";
import { PopulationDataProvider } from '@/store/PopulationDataContext';
import { PrefectureDataProvider } from '@/store/PrefectureDataContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="antialiased">
        <PrefectureDataProvider>
          <PopulationDataProvider>
            {children}
          </PopulationDataProvider>
        </PrefectureDataProvider>
      </body>
    </html>
  );
}
