import type { Metadata } from "next";
import "./globals.css";
import { PopulationDataProvider } from '@/store/PopulationDataContext';
import { PrefectureDataProvider } from '@/store/PrefectureDataContext';
import { ErrorStateProvider } from '@/store/ErrorStateContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="antialiased">
        <ErrorStateProvider>
          <PrefectureDataProvider>
            <PopulationDataProvider>
              {children}
            </PopulationDataProvider>
          </PrefectureDataProvider>
        </ErrorStateProvider>
      </body>
    </html>
  );
}
