import type { Metadata } from "next";
import "./globals.css";
import { PopulationDataProvider } from '@/store/PopulationDataContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <PopulationDataProvider>
          {children}
        </PopulationDataProvider>
      </body>
    </html>
  );
}
